type Channel {
	id: ID!
	name: String!
	messages: [Message]
}

type Message {
	channelId: ID!
	messageId: ID!
	content: String!
}

type Mutation {
	putChannel(id: ID!, name: String!): Channel
	deleteChannel(id: ID!): Channel
	putMessage(channelId: ID!, messageId: ID!, content: String!): Message
	deleteMessage(channelId: ID!, messageId: ID!): Message
}

type Query {
	allChannels: [Channel]
	getChannel(channelId: String): Channel
}

schema {
	query: Query
	mutation: Mutation
}
